name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: "Windows"
            os: windows-latest
            
          - name: "Linux"
            os: ubuntu-latest
        
          - name: "macOS"
            os: macos-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
          
      - name: Install dependencies
        run: |
          test
        if: matrix.name == 'Windows'
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libvulkan-dev
        if: matrix.name == 'Linux'

      - name: Install dependencies
        run: |
          test
        if: matrix.name == 'macOS'
        

      - name: Build Vision
        run: |
          cmake -S . -B ./bin/release -D CMAKE_BUILD_TYPE=Release
          cmake --build ./bin/release
