name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  Linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive 
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essentials cmake xorg-dev libvulkan-dev
         
      - name: Build Vision
        run: |
          cmake -S . -B ./bin/release -D CMAKE_BUILD_TYPE=Release
          cmake --build ./bin/release
